resources:
- name: ci
  type: git
  source:
    uri: https://github.com/ammar-hayder/new-ci-app.git
    branch: main

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: ci
    trigger: true
  - task: hello-world
    file: ci/tasks/lint.yml